{{- if (.Values.config) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- range $name,$value := .Values.config }}
  {{ $name | quote }}: |-
    scheduler:
      cron: {{ $value.scheduler.cron | quote }}
      retention: {{ $value.scheduler.retention }}
      timeout: {{ $value.scheduler.timeout }}
    {{- with $value.target }}
    target:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.encryption }}
    encryption:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.validation }}
    validation:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.retry }}
    retry:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.s3 }}
    s3:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.gcloud }}
    gcloud:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.azure }}
    azure:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.rclone }}
    rclone:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.sftp }}
    sftp:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.smtp }}
    smtp:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.slack }}
    slack:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
    {{- with $value.team }}
    team:
      {{ toYaml . | nindent 6 | trim }}
    {{- end }}
  {{- end }}
{{- end }}